Ковшов В.М. 23536/4  конвертация JSON в XML (пока без "обратно")
kit-cpp-course/kovshov-vm pull request #2
Opened 2018-12-23 23:46 UTC by prohladenn

Посмотрите пожалуйста что есть сейчас, потому что вторая часть работы будет сделана по образу и подобию.

2018-12-24 21:58 UTC, alpatov requested changes
Нужно поработать над структурой кода!!!

2018-12-24 21:58 UTC, alpatov commented on jsonSimple.h
> + * Мой обуительный класс
Так себе комментарий. Не информативно 👎

2018-12-24 21:58 UTC, alpatov commented on jsonSimple.h
> +class JSON {
Здесь, руководствуясь эталоном проектирования "Интерфейс", следует выделить абстрактный класс Parser, который будет описывать процесс Parsing-а в широком смысле.

2018-12-24 21:58 UTC, alpatov commented on jsonSimple.h
> +public:
Делая все компоненты общедоступными Вы нарушаете инкапсуляцию 👎

2018-12-24 21:58 UTC, alpatov commented on jsonSimple.h
> +bool JSON::isDigit(char c) {
Не вижу причины описывать методы в заголовочном файле. Сделайте cpp-файл.

2018-12-24 21:58 UTC, alpatov commented on jsonSimple.h
> +        } else if (JSON::isDigit(i) ||
Лучше не разбивать заголовок условного оператора на строчки. Его лучше писать в одной строке.

2018-12-24 21:58 UTC, alpatov commented on jsonSimple.h
> +vector<JSON::chunk> JSON::parseObject(const string &input) {
Очень процедурный код. Подумайте над тем, как можно сделать реализацию объектно-ориентированной.

2018-12-24 21:58 UTC, alpatov commented on main.cpp
> +    string input = "{\"menu\": {\n"
Лучше загружать текст из файла.

2018-12-24 21:58 UTC, alpatov commented on jsonSimple.h
> +class JSON {
Этот класс, хоть и написано в комментарии, что он решает одну задачу, на самом деле решает две задачи. Это плохо.
Класс должен решать одну задачу. Вам следует разделить этот класс на части: 

1. класс, описывающий элемент объектной модели; 
2. класс, выполняющий преобразование json-файла в объектную модель и обратно; 
3. класс, выполняющий .преобразование xml-файла в объектную модель и обратно.

При этом классы преобразователей должны быть наследниками одного абстрактного класса описывающего преобразователь в общем виде.

Объектная модель - древовидная структура, описывающая json/xml файлы.  Лучше всего с использованием эталона проектирования "Компоновщик"; он здесь будет очень к месту.

2018-12-24 21:58 UTC, alpatov commented on jsonSimple.cpp
> +vector<JSON::chunk> JSON::parse(const string &input) {
Слишком процедурный код. Нужно задуматься о его объектно-ориентированной реализации или увеличении уровня декомпозиции.

2018-12-24 21:58 UTC, alpatov commented on jsonSimple.cpp
> +string JSON::parseToXML() {
Слишком процедурный код. Нужно задуматься о его объектно-ориентированной реализации или увеличении уровня декомпозиции.

2018-12-24 21:58 UTC, prohladenn commented on jsonSimple.h
> + * Мой обуительный класс
Такс, это должно было быть удалено, простите, что вы это увидели

2018-12-24 22:00 UTC, prohladenn commented on jsonSimple.h
> +public:
Это на время разработки. Я отладку из main веду порой. В финальной версии всё это исправится

2019-01-13 22:17 UTC, prohladenn commented
Так как структура кода была изменена полностью от слова "совсем", решение переехало в новую ветку

2019-01-13 22:17 UTC, closed without merging